# Generated by Django 4.2.25 on 2025-11-10 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('content_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudysky_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('censored', models.BooleanField(default=False)),
                ('censored_reason', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudysky_app.media')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudysky_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('censored', models.BooleanField(default=False)),
                ('censored_reason', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudysky_app.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudysky_app.post')),
            ],
        ),
    ]
