# Generated by Django 5.2.7 on 2025-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudysky_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='censored_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='censored_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
